### ISSUE TITLE
Provisioning from TTN to C8Y duplicates device

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#20]
Provisionning a physical device from ttn LNS 

### scenario:

1. I setup a device in ttn side (physically, it's an adeunis lora field tester)

2. I trigger (push the button) a data tx
- the join procedure is processed (JR + JA visible in ttn logs)
- the device is created twice in cumulocity
   - one with the external id corresponding to the deveui
   - the other with no external Id set
 

3. I delete the 2 devices in C8Y side, then I trigger a new tx, the devices appear duped again in C8Y, both have external Id (the same = deveui)

**Comment by phcrb** [comment]
Precision: 
1. the first test did not show that behaviour
2. the process was done with another device (adeunis modbus) with the same duplicated result

**Comment by haraldmeyer** [comment]
Should this also be fixed with the other changes?

**Comment by cpoder** [comment]
Could you check that you don't have more than 1 connection on TTN side to Cumulocity?
This might also be solved by synchronizing the piece of code responsible for creating the device, but the reason that 2 uplinks are sent at the same time is mostly due to 2 connectors set on TTN, which is not good. This could have occurred with previous version of the framework where former connections were not properly updated/deleted upon microservice restarting.

**Comment by phcrb** [comment]
Indeed the ttn webhook was duplicated 
thanks for your analyze
