### ISSUE TITLE
Unprovisioning device from C8Y fails

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-lora#30]
When I want to deprovision a Objenious device from C8Y, I get the following error message:

The application requested these URL paths but your user is not allowed to access them PUT /service/actility/deprovision/2040

Is it a real issue or an application access permission problem (it is strange to make a request to Actility service) ?

**Comment by cpoder** [comment]
Apparently something is triggering the actility backend for some reason, probably because the framework is using the "provisioned" property which seems now to be used in a specific way by Cumulocity.
If your tenant is subscribed to Actility microservice, maybe try to disable it to see if this behavior still occurs.

**Comment by haraldmeyer** [comment]
This happens when using the "Delete device" button from the All Devices list as this triggers the standard Actility deprovisioning feature. Devices should be de-provisioned from the LoRa framework specific UI. 

As a separate change, the LoRa framework will be changed to not use the standard fragment that triggers the Actility feature.
