### ISSUE TITLE
missing custom config tab

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#51]
Hi, we noticed an issue on lora device management app. With the specifics codec developped by SAG for Greenflex in the scope of the Lora LNS integration project (in June 2021), it is possible to display the configuration applied to a device by an user using the "Text based configuration" tab of the devicemanagement-lora application. This tab shows the content of the c8y_Configuration fragment of the device.
![image](https://user-images.githubusercontent.com/84912886/148220324-31dde61b-3cb3-4f1a-b623-af976b37525c.png)

This feature works with the application version UI 1007.0.32 on the tenant https://gfx-energy.iot.greenflex.com/
But it no longer works with the application version UI 1009.0.18 on the tenant https://default-rd.dev.iot.greenflex.com/. The "Text based configuration" tab is not available despite the devices have a c8y_Configration fragment set.
![image](https://user-images.githubusercontent.com/84912886/148220371-f6a8be37-5653-45a4-9d8e-4873ffcab549.png)

Best regards
Philippe

**Comment by cpoder** [comment]
Hi,

Having a c8y_Configuration fragment doesn't display the "configuration" tab.
In order to display the configuration tab, and access the content of the c8y_Configuration fragment, the device must have a c8y_SupportedOperations fragment with c8y_Configuration in it as described in documentation: https://cumulocity.com/guides/reference/device-management-library/#install-text-configuration

**Comment by cpoder** [comment]
Please see latest commit which adds this supported operation by default.
